# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Address-Finder' do
  pod 'Alamofire', '~> 4.4'
  pod 'NMapsMap'
  pod 'SwiftLint'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Address-Finder

end
